name: "Lychee Broken Link Checker"
description: "Quickly check links in Markdown, HTML, and text files"

inputs:
  args:
    description: "Lychee arguments (https://github.com/lycheeverse/lychee#commandline-parameters)"
    default: "--verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'"
    required: false
  debug:
    description: "Enable debug output in action (set -x). Helpful for troubleshooting."
    default: false
    required: false
  fail:
    description: "Fail entire pipeline on error (i.e. when lychee exit code is not 0)"
    default: true
    required: false
  failIfEmpty:
    description: "Fail entire pipeline if no links were found"
    default: true
    required: false
  format:
    description: "Summary output format (e.g. json)"
    default: "markdown"
    required: false
  jobSummary:
    description: "Write GitHub job summary at the end of the job (written on Markdown output only)"
    default: true
    required: false
  lycheeVersion:
    description: "Use custom version of lychee link checker"
    default: v0.15.0
    required: false
  output:
    description: "Summary output file path"
    default: "lychee/out.md"
    required: false
  token:
    description: "Your GitHub Access Token, defaults to: {{ github.token }}"
    default: ${{ github.token }}
    required: false

outputs:
  exit_code:
    description: "The exit code returned from Lychee"
    value: ${{ steps.run-lychee.outputs.exit_code }}

runs:
  using: "composite"
  steps:
    - name: Set up environment
      run: |
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        mkdir -p "$HOME/.local/bin"
      shell: bash

    - name: Determine lychee filename
      id: lychee-filename
      run: |
        if [[ '${{ inputs.lycheeVersion }}' =~ ^v0\.0|^v0\.1[0-5]\. ]]; then
          echo "filename=lychee-${{ inputs.lycheeVersion }}-x86_64-unknown-linux-gnu.tar.gz" >> $GITHUB_OUTPUT
        else
          echo "filename=lychee-x86_64-unknown-linux-gnu.tar.gz" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Clean up existing lychee files
      run: |
        # Remove any existing lychee binaries or archives to prevent conflicts
        rm -f "$HOME/.local/bin/lychee"
        rm -f lychee
        rm -f "${{ steps.lychee-filename.outputs.filename }}"
      shell: bash

    - name: Download lychee
      run: |
        curl -sfLO "https://github.com/lycheeverse/lychee/releases/download/${{ inputs.lycheeVersion }}/${{ steps.lychee-filename.outputs.filename }}"
      shell: bash

    - name: Extract lychee
      run: |
        tar -xvzf "${{ steps.lychee-filename.outputs.filename }}"
      shell: bash

    - name: Install lychee
      run: |
        install -t "$HOME/.local/bin" -D lychee
      shell: bash

    - name: Clean up installation files
      run: |
        # Remove the downloaded archive and any unnecessary files after installation
        rm -f "${{ steps.lychee-filename.outputs.filename }}"
        shopt -s extglob
        rm -f lychee*!(lychee-bin|lychee-lib)
      shell: bash

    - name: Run lychee
      id: lychee
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        # https://github.com/actions/runner/issues/665
        INPUT_TOKEN: ${{ inputs.TOKEN }}
        INPUT_ARGS: ${{ inputs.ARGS }}
        INPUT_DEBUG: ${{ inputs.DEBUG }}
        INPUT_FAIL: ${{ inputs.FAIL }}
        INPUT_FAILIFEMPTY: ${{ inputs.FAILIFEMPTY }}
        INPUT_FORMAT: ${{ inputs.FORMAT }}
        INPUT_JOBSUMMARY: ${{ inputs.JOBSUMMARY }}
        INPUT_OUTPUT: ${{ inputs.OUTPUT }}
      shell: bash
branding:
  icon: "external-link"
  color: "purple"
