name: "Lychee Broken Link Checker"
description: "Quickly check links in Markdown, HTML, and text files"
inputs:
  args:
    description: "lychee arguments"
    default: "--verbose --no-progress './**/*.md' './**/*.html'"
    required: false
  format:
    description: "output format (e.g. json)"
    default: "markdown"
    required: false
  output:
    description: "output file"
    default: "lychee/out.md"
    required: false
  fail:
    description: "fail entire pipeline on error (exit code not 0)"
    default: false
    required: false
runs:
  using: "composite"
  steps:
    - name: install lychee
      run: |
        curl -LO 'https://github.com/lycheeverse/lychee/releases/download/v0.9.0/lychee-v0.9.0-x86_64-unknown-linux-gnu.tar.gz'
        tar -xvzf lychee-v0.9.0-x86_64-unknown-linux-gnu.tar.gz
        chmod 755 lychee
        mv lychee /usr/local/bin/lychee
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash

branding:
  icon: "external-link"
  color: "purple"
